version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: resto-hub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - resto-hub-network

  frontend:
    build:
      context: ./frontend
    container_name: resto-hub-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - resto-hub-network

networks:
  resto-hub-network:
    driver: bridge
