server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/menu/**
        
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
        
        - id: kitchen-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/kitchen/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
